language: php

php:
  - 5.5
  - 5.6
  - 7.0
  - hhvm

sudo: false

matrix:
  allow_failures:
    - php: 7.0
    - php: hhvm


test:
  adapter: mysql2
  database: emoji_test
  username: travis
  encoding: utf8

env:
  - DB=mysql

before_script:
  - composer install
  - mysql -e 'create database myapp_test;'
  - mysql -e 'use myapp_test'
  - mysql -e 'insert into users (username, password, names) values("danverem", "password", "Verem Dugeri");'

script:
   - bin/phpspec run --format=pretty
   - ./vendor/bin/phpunit --testdox
   - ./vendor/bin/behat --format=pretty --tags '~@php-version'`php php_version_tags.php`

after_script:
  - if [[ $TRAVIS_PHP_VERSION != 'hhvm' && $TRAVIS_PHP_VERSION != '7.0' ]]; then php vendor/bin/ocular code-coverage:upload --format=php-clover coverage.clover; fi
